### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by kevinschaul** [kevinschaul/binify#18]
.. probably does not exist yet. Is there enough interest?

**Comment by chagan** [comment]
I got this working on windows this weekend. Main issue was getting the gdal python bindings installed correctly, but there's a lot of documentation available. Haven't tested much yet, but maps look good so far in qgis.

**Comment by kevinschaul** [comment]
Nice. Did you have to make any changes to the code, or was the gdal installation the issue?

**Comment by chagan** [comment]
Yeah, only issues were with gdal. Got a missing DLL error initially but was able to reinstall from a different source and it worked out. No code changes yet, but I've only binned one smaller dataset so haven't really pushed it too much.

**Comment by kevinschaul** [comment]
That's encouraging. If you have a change, I'd love to have a set of Windows installation instructions in the readme. No worries if you don't, though.

I'll close this for now. If you run into issues later on, feel free to repoen it.
