### ISSUE TITLE
Option to ignore zero-count hexagons?

### ISSUE THREAD

**Issue by wilson428** [kevinschaul/binify#20]
I've been playing with binify for some data I gathered by geocoding about 30,000 addresses. I needed a `--num-across` value of about 200 to get the granularity I wanted, which created a huge .shp file. To get it in shape for graphing with d3, I converted to GeoJSON and wrote a short python script to remove all polygons where COUNT=0. After then converting to TopoJSON it got down to a very manageable 169KB. 

I thought this might make for a useful flag to the command line tool.

Would also be happy to publish this example as a gist or elsewhere. The final product looks great.

**Comment by kevinschaul** [comment]
Ah, yes. This would be very useful. Thanks for the suggestion.

I'd love to see what you've done. If you want to host it somewhere, I could point to it from an "In the wild" section of the readme.

**Comment by wilson428** [comment]
Great! I'll let you know when I post it.

On Tue, Apr 30, 2013 at 6:53 PM, Kevin Schaul notifications@github.comwrote:

> Ah, yes. This would be very useful. Thanks for the suggestion.
> 
> I'd love to see what you've done. If you want to host it somewhere, I
> could point to it from an "In the wild" section of the readme.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/kevinschaul/binify/issues/20#issuecomment-17259465
> .

## 

christopher.e.wilson@gmail.com
434.242.9728

**Comment by kevinschaul** [comment]
Let me know if this doesn't do what you hoped it would.

**Comment by wilson428** [comment]
Works like a charm, thanks! Will upload my example tonight.
